### ISSUE TITLE
Error in GraphiQL response - Unable to verify the first certificate

### ISSUE THREAD

**Issue by trelloscy** [groupon/swagql#19]
I was able to generate a GraphQL schema from my Swagger documentation using SwagQL, start an Express node.js server and open GraphiQL locally on my browser.

The problem is, whenever I try to query any of my endpoints I keep getting the error "Unable to verify the first certificate";
Is this a client issue or a server issue?

**Comment by dbushong** [comment]
It sounds like that's an OpenSSL error likely triggered by trying to run your Node server with a self-signed certificate.  If you're using `curl` to test, you can pass `-k` to have it ignore certificate issues.

Note that this is not a swagql-related problem, but hopefully that will help.

**Comment by trelloscy** [comment]
Indeed I was missing an FQDN SSL certificate on my IIS, as soon as I added it everything worked correctly 👍 

Honestly appreciate the prompt reply!
