### ISSUE TITLE
Yarn is not supported

### ISSUE THREAD

**Issue by zfmaster** [groupon/swagql#22]
### Description
When trying to install using yarn the error is shown:

```
error swagql@1.3.7: The engine "yarn" is incompatible with this module. Expected version "0.0.0". Got "1.22.5"
error Found incompatible module.
```

**Comment by aaarichter** [comment]
@zfmaster hi - sorry for the late reply and this yarn blocker. I opened a PR to fix this https://github.com/groupon/swagql/pull/23
