### ISSUE TITLE
preinstall script causes install failure

### ISSUE THREAD

**Issue by jspears** [groupon/swagql#5]
The preinstall script
`fgrep -ql package-lock.json .gitignore || npm -v | egrep -q '^6\.'`

fails when there is no `.gitignore` .

**Comment by jkrems** [comment]
Thanks for the report!

@dbushong Should we remove that script? I don't think it takes into account running when installing it from npm, only local development..?

**Comment by jkrems** [comment]
Should be fixed via https://github.com/groupon/swagql/pull/7
